In [ ]:
# Data manipulation
import pandas as pd
pd.set_option('display.max_columns', None)

# System paths for module importing
import sys 
sys.path.append('../')

# Custom utility functions
import src.eda_utils as eu

In [ ]:
df=pd.read_csv("../data/data_raw.csv")

In [3]:
eu.baseline_eda(df)

--- RANDOM SAMPLE ---

,User Id,Group,Visit Date,Conversion,Product Category,Product Id,Product Name,Quantity,Price,Discount,Total Value,Payment Method,Shipping Method,Region,Customer Age,Customer Gender,Device,Session Duration,Coupon Used,Browser,Referral Source
602,603,A,2022-01-27,0,BOOKS,P1158,Mystery,0,"7,25","0,23","0,0",NaN,NaN,Central,50.0,M,Desktop,19,NaN,Eddddge,Email
441,442,B,2022-02-20,1,FASHHION,P1276,Dress,5,"177,54","0,23","683,53",Bank Transfer,Standard,East,50.0,F,TABLET,5,No,Firefoxxxxxx,PAID
134,135,B,2022-01-12,0,SPORTS,P1192,Running Shoes,0,"165,77","0,09","0,0",NaN,NaN,South,43.0,M,TABLET,30,NaN,Safaaaaari,Email
269,270,A,2022-03-20,1,TOYS,P1415,Puzzle,1,"31,74","0,06","29,84",Credit Card,Same day,Central,34.0,F,Desktop,9,No,Safaaaaari,Email
1491,1492,A,2022-01-24,0,SPORTS,P1064,Football,0,"244,11","0,11","0,0",NaN,NaN,East,54.0,M,Desktop,2,NaN,Eddddge,PAID

--- DIMENSIONS ---
Our dataset has 2000 rows and 21 columns.

--- INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   User Id           2000 non-null   int64
 1   Group             2000 non-null   object
 2   Visit Date        2000 non-null   object
 3   Conversion        2000 non-null   int64
 4   Product Category  2000 non-null   object
 5   Product Id        2000 non-null   object
 6   Product Name      2000 non-null   object
 7   Quantity          2000 non-null   int64
 8   Price             1960 non-null   object
 9   Discount          1960 non-null   object
 10  Total Value       2000 non-null   object
 11  Payment Method    247 non-null    object
 12  Shipping Method   247 non-null    object
 13  Region            2000 non-null   object
 14  Customer Age      1960 non-null   float64
 15  Customer Gender   2000 non-null   object
 16  Device            2000 non-null   object
 17  Session Duration  2000 non-null   int64
 18  Coupon Used       247 non-null    object
 19  Browser           2000 non-null   object
 20  Referral Source   2000 non-null   object
dtypes: float64(1), int64(4), object(16)
memory usage: 328.3+ KB

--- MISSING VALUES (%) ---

User Id              0.00
Group                0.00
Visit Date           0.00
Conversion           0.00
Product Category     0.00
Product Id           0.00
Product Name         0.00
Quantity             0.00
Price                2.00
Discount             2.00
Total Value          0.00
Payment Method      87.65
Shipping Method     87.65
Region               0.00
Customer Age         2.00
Customer Gender      0.00
Device               0.00
Session Duration     0.00
Coupon Used         87.65
Browser              0.00
Referral Source      0.00
dtype: float64

--- DUPLICATES ---
Total duplicated rows: 0

--- CATEGORICAL VALUE COUNTS ---

GROUP:
Group
B    1013
A     987
Name: count, dtype: int64
-----------

VISIT DATE:
Visit Date
2022-01-28    35
2022-02-16    34
2022-02-28    32
2022-01-19    31
2022-01-21    31
              ..
2022-01-18    15
2022-03-21    14
2022-03-30    14
2022-02-21    12
2022-01-31    10
Name: count, Length: 90, dtype: int64
-----------

PRODUCT CATEGORY:
Product Category
FASHHION       321
BOOKS          291
HOME           287
SPORTS         282
TOYS           276
ELECTRONICS    275
BEAUTY         268
Name: count, dtype: int64
-----------

PRODUCT ID:
Product Id
P1416    8
P1782    8
P1848    7
P1605    7
P1798    7
        ..
P1774    1
P1096    1
P1120    1
P1196    1
P1805    1
Name: count, Length: 867, dtype: int64
-----------

PRODUCT NAME:
Product Name
Science Fiction    85
Smartphone         84
Jeans              84
Mystery            82
Table              82
Sofa               82
Dress              81
Sneakers           81
Football           77
Action Figure      75
T-shirt            75
Mascara            74
Doll               73
Headphones         72
Lamp               72
Running Shoes      72
Tennis Racket      72
Perfume            71
Novel              69
Lipstick           69
Board Game         69
Gym Bag            61
Camera             60
Puzzle             59
Laptop             59
Biography          55
Lotion             54
Chair              51
Name: count, dtype: int64
-----------

PRICE:
Price
NaN       40
19,99      3
22,8       2
38,12      2
84,13      2
          ..
198,08     1
14,01      1
498,58     1
102,32     1
433,07     1
Name: count, Length: 1888, dtype: int64
-----------

DISCOUNT:
Discount
0,08    76
0,21    76
0,03    75
0,27    75
0,01    74
0,25    74
0,13    74
0,19    73
0,22    71
0,29    70
0,17    70
0,1     70
0,16    67
0,12    66
0,24    66
0,14    64
0,02    64
0,11    63
0,04    62
0,2     62
0,23    62
0,07    62
0,05    58
0,09    58
0,26    58
0,28    55
0,15    54
0,06    53
0,18    53
NaN     40
0,0     29
0,3     26
Name: count, dtype: int64
-----------

TOTAL VALUE:
Total Value
0,0       1753
871,24       1
109,22       1
66,67        1
69,26        1
          ...
20,02        1
61,41        1
752,46       1
8,19         1
437,85       1
Name: count, Length: 248, dtype: int64
-----------

PAYMENT METHOD:
Payment Method
NaN                 1753
Bank Transfer         73
Credit Card           67
PayPal                57
Cash on Delivery      50
Name: count, dtype: int64
-----------

SHIPPING METHOD:
Shipping Method
NaN         1753
Express       90
Same day      82
Standard      75
Name: count, dtype: int64
-----------

REGION:
Region
South      435
East       402
Central    398
North      396
West       369
Name: count, dtype: int64
-----------

CUSTOMER GENDER:
Customer Gender
F        997
M        915
Other     88
Name: count, dtype: int64
-----------

DEVICE:
Device
TABLET     696
Mobile     676
Desktop    628
Name: count, dtype: int64
-----------

COUPON USED:
Coupon Used
NaN    1753
No      132
Yes     115
Name: count, dtype: int64
-----------

BROWSER:
Browser
Ottttther       443
Eddddge         431
Chrooome        411
Firefoxxxxxx    365
Safaaaaari      350
Name: count, dtype: int64
-----------

REFERRAL SOURCE:
Referral Source
Organic    551
Social     493
Email      482
PAID       474
Name: count, dtype: int64
-----------

--- NUMERICAL STATISTICS ---

,count,mean,std,min,25%,50%,75%,max
User Id,2000.0,1000.500000,577.494589,1.0,500.75,1000.5,1500.25,2000.0
Conversion,2000.0,0.123500,0.329093,0.0,0.00,0.0,0.00,1.0
Quantity,2000.0,0.371000,1.096339,0.0,0.00,0.0,0.00,5.0
Customer Age,1960.0,43.156633,15.361675,18.0,30.00,42.0,56.00,70.0
Session Duration,2000.0,15.633500,8.692235,1.0,8.00,16.0,23.00,30.0