In [41]:
# Data manipulation
import pandas as pd
pd.set_option('display.max_columns', None)

# System paths for module importing
import sys 
sys.path.append('../')

# Custom utility functions
from src import data_cleaning_utils as dcu

In [42]:
df_raw=pd.read_csv("../data/data_raw.csv")
df_raw.sample(5)

,User Id,Group,Visit Date,Conversion,Product Category,Product Id,Product Name,Quantity,Price,Discount,Total Value,Payment Method,Shipping Method,Region,Customer Age,Customer Gender,Device,Session Duration,Coupon Used,Browser,Referral Source
421,422,B,2022-02-15,0,ELECTRONICS,P1707,Smartphone,0,"344,96","0,17","0,0",NaN,NaN,Central,31.0,F,TABLET,14,NaN,Chrooome,PAID
1319,1320,A,2022-02-03,0,BEAUTY,P1207,Lotion,0,"12,96","0,18","0,0",NaN,NaN,East,30.0,F,Mobile,16,NaN,Firefoxxxxxx,Email
219,220,B,2022-02-03,1,BOOKS,P1403,Mystery,4,"39,19","0,23","120,71",Cash on Delivery,Express,East,39.0,F,TABLET,6,Yes,Chrooome,Social
1101,1102,B,2022-01-06,0,FASHHION,P1742,Sneakers,0,NaN,"0,14","0,0",NaN,NaN,Central,20.0,M,TABLET,24,NaN,Safaaaaari,Organic
1795,1796,A,2022-01-26,0,BEAUTY,P1716,Lotion,0,"109,4","0,17","0,0",NaN,NaN,South,20.0,F,Mobile,8,NaN,Eddddge,PAID

In [43]:
df=df_raw.copy()

## Standardize column names

In [ ]:
df.columns=df.columns.str.replace(" ","_").str.lower()

## Convert visit_date column to datetime format

In [45]:
df['visit_date']=pd.to_datetime(df['visit_date'],format='%Y-%m-%d')

## Create human-readable Conversion string column

In [46]:
df['conversion_str']=df['conversion'].apply(lambda x: 'yes' if x==1 else 'no')

In [47]:
df.loc[:,['conversion','conversion_str']].sample(5)

      conversion conversion_str
1971           0             no
1178           0             no
1972           0             no
1194           1            yes
992            0             no

## Replace spaces with underscores

In [48]:
dcu.replace_spaces_with_underscores(df)

## Standarize decimal separators and convert to float

In [49]:
dcu.convert_commas_to_dots(df)

## Convert all string columns to lowercase

In [50]:
dcu.lowercase_strings(df)

In [51]:
df.sample(5)

,user_id,group,visit_date,conversion,product_category,product_id,product_name,quantity,price,discount,total_value,payment_method,shipping_method,region,customer_age,customer_gender,device,session_duration,coupon_used,browser,referral_source,conversion_str
761,762,a,2022-01-05,0,toys,p1083,board_game,0,84.06,0.24,0.0,NaN,NaN,north,31.0,m,mobile,26,NaN,ottttther,email,no
1045,1046,b,2022-03-31,0,home,p1410,lamp,0,165.42,0.05,0.0,NaN,NaN,south,NaN,f,tablet,30,NaN,chrooome,paid,no
423,424,a,2022-01-08,0,sports,p1207,gym_bag,0,154.06,0.10,0.0,NaN,NaN,east,30.0,m,mobile,24,NaN,ottttther,paid,no
1621,1622,a,2022-01-28,0,beauty,p1202,mascara,0,70.82,0.08,0.0,NaN,NaN,west,18.0,m,tablet,29,NaN,firefoxxxxxx,social,no
1713,1714,a,2022-02-26,0,beauty,p1185,mascara,0,74.65,0.16,0.0,NaN,NaN,north,39.0,m,desktop,25,NaN,eddddge,organic,no

## Clean Product Category: Fix 'FASHHION' typo to 'Fashion'

In [52]:
df['product_category']=df['product_category'].str.replace('fashhion','fashion')

In [53]:
df.sample(5)

,user_id,group,visit_date,conversion,product_category,product_id,product_name,quantity,price,discount,total_value,payment_method,shipping_method,region,customer_age,customer_gender,device,session_duration,coupon_used,browser,referral_source,conversion_str
1368,1369,a,2022-02-01,0,books,p1573,biography,0,24.57,0.24,0.0,NaN,NaN,north,70.0,f,desktop,1,NaN,ottttther,paid,no
358,359,b,2022-01-08,0,books,p1175,novel,0,16.28,0.03,0.0,NaN,NaN,south,33.0,m,tablet,29,NaN,chrooome,paid,no
212,213,b,2022-01-28,0,beauty,p1470,perfume,0,47.14,0.28,0.0,NaN,NaN,south,30.0,f,desktop,16,NaN,firefoxxxxxx,email,no
1806,1807,b,2022-02-20,0,home,p1563,sofa,0,226.33,0.27,0.0,NaN,NaN,north,65.0,m,mobile,13,NaN,firefoxxxxxx,social,no
647,648,b,2022-03-04,0,toys,p1269,board_game,0,61.68,0.25,0.0,NaN,NaN,east,35.0,f,desktop,2,NaN,safaaaaari,organic,no

## Clean Product id: Strip 'P' prefix and convert to numeric

In [54]:
df['product_id']=df['product_id'].str.replace('p','')
df['product_id']=df['product_id'].astype('Int64')

## Clean Browser Column using a descriptive map

In [55]:
df['browser'].unique()

array(['safaaaaari', 'ottttther', 'firefoxxxxxx', 'eddddge', 'chrooome'],
      dtype=object)

In [56]:
browser_clean_map={'safaaaaari': 'safari',
         'ottttther':'other',
         'firefoxxxxxx':'firefox',
        'eddddge': 'edge',
         'chrooome': 'chrome' }

In [57]:
df['browser']=df['browser'].map(browser_clean_map)

In [58]:
df.to_csv('../data/data_cleaned.csv',index=False)